openai:
    historyGeneratedPrompt: 5
    rewardEmoji: "ğŸª"
    historyTtl: 600 # secondes
    timeZoneDelta: 0

openai-vsion:
    historyGeneratedPrompt: 5
    rewardEmoji: "ğŸª"
    historyTtl: 600 # secondes
    timeZoneDelta: 0

app:
    ignoreMyself: false  #ignore the bot's answers in the generated prompt 
    mentionsOnly: false
    chanceToAddOneMoreAnswer: 10 # %
    slowModeTime: 15
    ignoreMentionInPromps: false #todo
    reactionWords: 
        - "Hello"